[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

xset -b
fcitx -d
#sh ~/.fehbg &
# hack to make systemd communicating with dunst
#systemctl --user set-environment DISPLAY=:0
#exec xmonad
exec awesome
