ANTIGEN_DIR="${HOME}/.local/share/antigen"
ANTIGEN_PATH="${ANTIGEN_DIR}/antigen.zsh"
if [ -f "${ANTIGEN_PATH}" ] ; then
  source "${ANTIGEN_PATH}"
  antigen bundle zsh-users/zsh-completions
  antigen theme "${HOME}/dotfiles/z/themes" ilyaletre
  antigen apply
fi

bindkey -M viins '^P' history-beginning-search-backward
bindkey -M viins '^N' history-beginning-search-forward
bindkey -M viins "^R" history-incremental-pattern-search-backward
bindkey -M viins "^S" history-incremental-pattern-search-forward
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^B' backward-char
bindkey -M viins '^D' delete-char-or-list
bindkey -M viins '^E' end-of-line
bindkey -M viins '^F' forward-char
bindkey -M viins '^G' send-break
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^K' kill-line
bindkey -M viins '^U' backward-kill-line
bindkey -M viins '^W' backward-kill-word
bindkey -M viins '^Y' yank


export GOPATH="${HOME}/projects/go"

alias mute="amixer set Master mute"
alias unmute="amixer set Master unmute"
alias sup="amixer set Master 5%+"
alias sdown="amixer set Master 5%-"
alias suspend="systemctl suspend"
alias ku="kubectl"
alias less='less -Q'
alias man='man -P "less -Q"'
alias nshell="nix-shell --command /usr/bin/zsh"
alias rsend="rsync -av"

eval "$(rbenv init -)"

# disable terminal control flow
stty -ixon

