autoload -Uz compinit promptinit vcs_info
compinit

# Prompt
promptinit
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
export PS1='[%n@%m %1~]%(#.#.$) '
export PS2="> "
prompt_opts=( cr percent )

bindkey -M viins '^P' history-beginning-search-backward
bindkey -M viins '^N' history-beginning-search-forward
bindkey -M viins "^R" history-incremental-pattern-search-backward
bindkey -M viins "^S" history-incremental-pattern-search-forward
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^B' backward-char
bindkey -M viins '^D' delete-char-or-list
bindkey -M viins '^E' end-of-line
bindkey -M viins '^F' forward-char
bindkey -M viins '^G' send-break
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^K' kill-line
bindkey -M viins '^U' backward-kill-line
bindkey -M viins '^W' backward-kill-word
bindkey -M viins '^Y' yank

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export GOPATH="${HOME}/projects/go"

alias mute="amixer set Master mute"
alias unmute="amixer set Master unmute"
alias sup="amixer set Master 5%+"
alias sdown="amixer set Master 5%-"
alias suspend="systemctl suspend"
alias ku="kubectl"
alias less='less -Q'
alias man='man -P "less -Q"'
alias nshell="nix-shell --command /usr/bin/zsh"
alias rsend="rsync -av"

eval "$(rbenv init -)"

# disable terminal control flow
stty -ixon


