#!/usr/bin/bash

brew update

brew upgrade

brew install libpng
brew install lua
brew install luajit
brew install libtiff
brew install gettext
brew install jpeg

brew install fontforge

#brew install macvim

#brew install groovy

#brew install gradle

brew install acscope

#brew install scala

#brew install sbt

#brew install play

brew install imagemagick

brew install ssreflect
