#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import fnmatch
import os
import os.path as path
import functools

EXCLUDE_FILES = (".git", "*.markdown")

def isexcluded(f):
    for e in EXCLUDE_FILES:
        if fnmatch.fnmatch(f, e):
            return True
    return False

def main(args):
    if 1 < len(args):
        targetdir = args[1]
    else:
        targetdir = path.expanduser("~")

    jointarget = functools.partial(join, targetdir)

    scriptpath = __file__
    basedir = path.dirname(scriptpath)
    sourcefiles = [s for s in os.listdir(basedir) if not isexcluded(s)]

    filenames = [path.basename(s) for s in sourcefiles]
    dotted = ["." + f for f in filenames]
    targetfiles = [path.join(targetdir, f) for f in dotted]

    for (s, t) in zip(sourcefiles, targetfiles):
        os.symlink(s, t)

    return targetfiles

if __name__ == "__main__":
    main(sys.argv)
