#!/bin/sh


SCRIPTDIR=`dirname $0`
TARGET=${HOME}

pushd ${SCRIPTDIR}
DOTFILES=$(pwd)
popd 

if [ -d "$1" ] ; then
    TARGET=$1
fi

if [ -z "${TARGET}" ] ; then
    echo "Usage: target-path"
    exit 1
fi

function setup_nix() {

    which nix-env
    local nixenvexists=$?

    if [ ${nixenvexists} -ne 0 ] ; then
        echo "Installing nix..."
        curl https://nixos.org/nix/install | sh
    else
        echo "Nix has already been installed. Skip installing."
    fi
    

    if [ ! -f "/etc/nix/nix.conf" ] ; then
        echo "Creation /etc/nix/nix.conf ...."

        sudo mkdir -p /etc/nix
        echo "binary-caches = http://zalora-public-nix-cache.s3-website-ap-southeast-1.amazonaws.com/ http://cache.nixos.org/" | sudo tee /etc/nix/nix.conf
    fi

    
    echo "Creating local nix config..."
    mkdir -p "${HOME}/.nixpkgs"
    pushd "${HOME}/.nixpkgs"
    ln -s "${DOTFILES}/config.nix" "config.nix"
    popd

}

# fonts fot MacVim powerline
function download_font() {
    local fontdir="${HOME}/Library/Fonts"
    if [ ! -d "${fontdir}" ] ; then
        mkdir -p "${fontdir}"
    fi
    pushd ${fontdir}
    if [ -d "${fontdir}/fonts" ] ; then
        pushd fonts
        git pull
        popd
    else
        git clone https://github.com/powerline/fonts.git
    fi
    popd
}

function copy_dotfiles() {
    homefiles="ghci gvimrc vimrc zshrc gitconfig zshenv"
    pushd "${TARGET}"
    for i in ${homefiles} ; do
      ln -fs "${DOTFILES}/$i" ".$i"
    done
    popd
}

function install_ohmyzsh() {
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

function install_vundle() {
    local bundle_path="${HOME}/.vim/bundle"
    mkdir -p ${bundle_path}
    git clone https://github.com/gmarik/Vundle.vim.git ${bundle_path}/Vundle.vim
    cp ilyaletre.zsh-theme ${HOME}/.oh-my-zsh/themes
}

function main() {
    copy_dotfiles
    setup_nix
}


main
